[package]
name = "dsmr-assignment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1"
itertools = "0.11"
tudelft-dsmr-output-generator = "*"
derive_more = "0.99.13"
cmake = "0.1.50"
